# Generated by Django 6.0.4 on 2026-05-01 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mint_address', models.CharField(max_length=100, unique=True)),
                ('symbol', models.CharField(max_length=50)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('confidence', models.FloatField(default=0)),
                ('buy_signal', models.FloatField(default=0)),
                ('sell_signal', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('trade_type', models.CharField(max_length=10)),
                ('market_cap', models.FloatField()),
                ('amount_usd', models.FloatField()),
                ('price_usd', models.FloatField()),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.token')),
            ],
        ),
    ]
